"""Initial schema

Revision ID: a3d91e0b936a
Revises: 
Create Date: 2025-11-13 11:43:11.713795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3d91e0b936a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('annotation_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_history_annotation_id'), 'annotation_history', ['annotation_id'], unique=False)
    op.create_index('ix_annotation_history_annotation_timestamp', 'annotation_history', ['annotation_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_annotation_history_project_id'), 'annotation_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_annotation_history_timestamp'), 'annotation_history', ['timestamp'], unique=False)
    op.create_table('annotation_projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('task_types', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('task_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_images', sa.Integer(), nullable=True),
    sa.Column('annotated_images', sa.Integer(), nullable=True),
    sa.Column('total_annotations', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_projects_created_at'), 'annotation_projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_annotation_projects_dataset_id'), 'annotation_projects', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_annotation_projects_owner_id'), 'annotation_projects', ['owner_id'], unique=False)
    op.create_index('ix_annotation_projects_owner_id_created_at', 'annotation_projects', ['owner_id', 'created_at'], unique=False)
    op.create_table('annotation_tasks',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('image_ids', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('total_images', sa.Integer(), nullable=True),
    sa.Column('completed_images', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_tasks_assignee_id'), 'annotation_tasks', ['assignee_id'], unique=False)
    op.create_index('ix_annotation_tasks_assignee_status', 'annotation_tasks', ['assignee_id', 'status'], unique=False)
    op.create_index(op.f('ix_annotation_tasks_project_id'), 'annotation_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_annotation_tasks_status'), 'annotation_tasks', ['status'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('annotation_type', sa.String(length=20), nullable=False),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('class_id', sa.String(length=50), nullable=True),
    sa.Column('class_name', sa.String(length=255), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_annotation_type'), 'annotations', ['annotation_type'], unique=False)
    op.create_index(op.f('ix_annotations_created_at'), 'annotations', ['created_at'], unique=False)
    op.create_index('ix_annotations_created_by', 'annotations', ['created_by'], unique=False)
    op.create_index(op.f('ix_annotations_image_id'), 'annotations', ['image_id'], unique=False)
    op.create_index(op.f('ix_annotations_project_id'), 'annotations', ['project_id'], unique=False)
    op.create_index('ix_annotations_project_image', 'annotations', ['project_id', 'image_id'], unique=False)
    op.create_index('ix_annotations_project_type', 'annotations', ['project_id', 'annotation_type'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('image_id', sa.String(length=255), nullable=False),
    sa.Column('annotation_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_annotation_id'), 'comments', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_image_id'), 'comments', ['image_id'], unique=False)
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    op.create_index('ix_comments_project_image', 'comments', ['project_id', 'image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_project_image', table_name='comments')
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_image_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_annotation_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_annotations_project_type', table_name='annotations')
    op.drop_index('ix_annotations_project_image', table_name='annotations')
    op.drop_index(op.f('ix_annotations_project_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_image_id'), table_name='annotations')
    op.drop_index('ix_annotations_created_by', table_name='annotations')
    op.drop_index(op.f('ix_annotations_created_at'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_annotation_type'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_annotation_tasks_status'), table_name='annotation_tasks')
    op.drop_index(op.f('ix_annotation_tasks_project_id'), table_name='annotation_tasks')
    op.drop_index('ix_annotation_tasks_assignee_status', table_name='annotation_tasks')
    op.drop_index(op.f('ix_annotation_tasks_assignee_id'), table_name='annotation_tasks')
    op.drop_table('annotation_tasks')
    op.drop_index('ix_annotation_projects_owner_id_created_at', table_name='annotation_projects')
    op.drop_index(op.f('ix_annotation_projects_owner_id'), table_name='annotation_projects')
    op.drop_index(op.f('ix_annotation_projects_dataset_id'), table_name='annotation_projects')
    op.drop_index(op.f('ix_annotation_projects_created_at'), table_name='annotation_projects')
    op.drop_table('annotation_projects')
    op.drop_index(op.f('ix_annotation_history_timestamp'), table_name='annotation_history')
    op.drop_index(op.f('ix_annotation_history_project_id'), table_name='annotation_history')
    op.drop_index('ix_annotation_history_annotation_timestamp', table_name='annotation_history')
    op.drop_index(op.f('ix_annotation_history_annotation_id'), table_name='annotation_history')
    op.drop_table('annotation_history')
    # ### end Alembic commands ###
