"""Add service_accounts table for Phase 16 Platform integration

Revision ID: 20f9d474c620
Revises: 20251126_1400
Create Date: 2025-11-27 21:41:21.534766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20f9d474c620'
down_revision: Union[str, None] = '20251126_1400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_accounts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_index('idx_service_accounts_created_by', 'service_accounts', ['created_by'], unique=False)
    op.create_index('idx_service_accounts_is_active', 'service_accounts', ['is_active'], unique=False)
    op.create_index('idx_service_accounts_service_name', 'service_accounts', ['service_name'], unique=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('ix_audit_logs_status', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_timestamp_desc', 'audit_logs', [sa.text('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_image_locks_image_id'), 'image_locks', ['image_id'], unique=False)
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_system_stats_cache_id'), 'system_stats_cache', ['id'], unique=False)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.String(length=50),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_index(op.f('ix_system_stats_cache_id'), table_name='system_stats_cache')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_image_locks_image_id'), table_name='image_locks')
    op.drop_index('ix_audit_logs_timestamp_desc', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_index('ix_audit_logs_status', 'audit_logs', ['status'], unique=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=50),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_index('idx_service_accounts_service_name', table_name='service_accounts')
    op.drop_index('idx_service_accounts_is_active', table_name='service_accounts')
    op.drop_index('idx_service_accounts_created_by', table_name='service_accounts')
    op.drop_table('service_accounts')
    # ### end Alembic commands ###
