"""Add image_metadata table for performance optimization

Revision ID: e538081f9c62
Revises: f9a0b1c2d3e4
Create Date: 2025-11-21 19:56:35.299694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e538081f9c62'
down_revision: Union[str, None] = 'f9a0b1c2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_metadata',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('dataset_id', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('folder_path', sa.String(length=1000), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_metadata_dataset', 'image_metadata', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_image_metadata_dataset_id'), 'image_metadata', ['dataset_id'], unique=False)
    op.create_index('ix_image_metadata_folder', 'image_metadata', ['dataset_id', 'folder_path'], unique=False)
    op.create_index('ix_image_metadata_uploaded', 'image_metadata', ['dataset_id', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_annotation_snapshots_annotation_id'), 'annotation_snapshots', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_annotation_snapshots_version_id'), 'annotation_snapshots', ['version_id'], unique=False)
    op.alter_column('annotations', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_annotations_task_type'), 'annotations', ['task_type'], unique=False)
    op.drop_index('ix_dataset_permissions_dataset', table_name='dataset_permissions')
    op.drop_index('ix_dataset_permissions_role', table_name='dataset_permissions')
    op.drop_index('ix_dataset_permissions_user', table_name='dataset_permissions')
    op.create_index(op.f('ix_dataset_permissions_dataset_id'), 'dataset_permissions', ['dataset_id'], unique=False)
    op.create_index('ix_dataset_permissions_dataset_user', 'dataset_permissions', ['dataset_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_dataset_permissions_user_id'), 'dataset_permissions', ['user_id'], unique=False)
    op.drop_index('ix_datasets_created_at', table_name='datasets')
    op.drop_index('ix_datasets_owner_created', table_name='datasets')
    op.drop_index('ix_datasets_status', table_name='datasets')
    op.create_index('ix_datasets_owner_id_created_at', 'datasets', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_image_annotation_status_image_id'), 'image_annotation_status', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_annotation_status_image_id'), table_name='image_annotation_status')
    op.drop_index('ix_datasets_owner_id_created_at', table_name='datasets')
    op.create_index('ix_datasets_status', 'datasets', ['status'], unique=False)
    op.create_index('ix_datasets_owner_created', 'datasets', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_datasets_created_at', 'datasets', ['created_at'], unique=False)
    op.drop_index(op.f('ix_dataset_permissions_user_id'), table_name='dataset_permissions')
    op.drop_index('ix_dataset_permissions_dataset_user', table_name='dataset_permissions')
    op.drop_index(op.f('ix_dataset_permissions_dataset_id'), table_name='dataset_permissions')
    op.create_index('ix_dataset_permissions_user', 'dataset_permissions', ['user_id'], unique=False)
    op.create_index('ix_dataset_permissions_role', 'dataset_permissions', ['role'], unique=False)
    op.create_index('ix_dataset_permissions_dataset', 'dataset_permissions', ['dataset_id'], unique=False)
    op.drop_index(op.f('ix_annotations_task_type'), table_name='annotations')
    op.alter_column('annotations', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_annotation_snapshots_version_id'), table_name='annotation_snapshots')
    op.drop_index(op.f('ix_annotation_snapshots_annotation_id'), table_name='annotation_snapshots')
    op.drop_index('ix_image_metadata_uploaded', table_name='image_metadata')
    op.drop_index('ix_image_metadata_folder', table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_dataset_id'), table_name='image_metadata')
    op.drop_index('ix_image_metadata_dataset', table_name='image_metadata')
    op.drop_table('image_metadata')
    # ### end Alembic commands ###
