"""add last_updated_by to annotation_projects

Revision ID: ead03dbc7300
Revises: d272076582e4
Create Date: 2025-11-13 17:39:01.408624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead03dbc7300'
down_revision: Union[str, None] = 'd272076582e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_projects', sa.Column('last_updated_by', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_annotation_projects_last_updated_by'), 'annotation_projects', ['last_updated_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_projects_last_updated_by'), table_name='annotation_projects')
    op.drop_column('annotation_projects', 'last_updated_by')
    # ### end Alembic commands ###
